In [ ]:
import numpy as np
list1=[1, 2, 3, 4]
arr=np.array(list1)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
tple= (1, 2, 3)
arr=np.array(tple)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
l=np.zeros((5), dtype='i') #i= integer f=float
print(l)

[0 0 0 0 0]


In [ ]:
l=np.zeros(5)
print(l)

[0. 0. 0. 0. 0.]


In [ ]:
# task1
import numpy as np
def playRight(sequence, beats):
  for i in beats:
    if i==1:
      c=sequence[len(sequence)-1]
      for j in range (len(sequence)-1,0,-1):
        sequence[j]=sequence[j-1]
      sequence[0]=c
  return sequence


print("///  Test 01: Play Right  ///")
sequence=np.array([10,20,30,40,50,60])
beats = np.array([1,0,0,1,0,1])
returned_value = playRight(sequence, beats) 
print(f'Task 1: {returned_value}') # This should print [40, 50, 60, 10, 20, 30]
# unittest.output_test(returned_value, np.array([40, 50, 60, 10, 20, 30]))


///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]


In [ ]:
#Task02
import numpy as np
def discardCards (cards, n):
  for i in range (0, len(cards)):
    if cards[i]==n:
      cards[i]=cards[i+1]
      



print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, None, None, None, None]
# unittest.output_test(returned_value, [1, 3, 8, 5, 7, None, None, None, None])

///  Test 02: Discard Cards  ///


TypeError: ignored