In [ ]:
array_1d=[None]*5
print(array_1d)

[None, None, None, None, None]


In [ ]:
array_2d=[None]*5
for i in range (len(array_2d)):
  array_2d[i]=[None]*5
print (array_2d)

[[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]]


In [ ]:
# 3 dimentional array using python
array_3d=[None]*5
for i in range (len(array_3d)):
  array_3d[i]=[None]*5
  for j in range (len(array_3d[i])):
    array_3d[i][j]=[None]*5
print (array_3d)

[[[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]], [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]], [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]], [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]], [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]]]


In [2]:
import numpy as np
arr = np.zeros((4,5,6,), dtype='int')
for i in range (arr.shape[0]):
  for j in range (arr.shape[1]):
    for k in range (arr.shape[2]):
      arr[i][j][k]=i*100+j*10+k
print (arr)

[[[  0   1   2   3   4   5]
  [ 10  11  12  13  14  15]
  [ 20  21  22  23  24  25]
  [ 30  31  32  33  34  35]
  [ 40  41  42  43  44  45]]

 [[100 101 102 103 104 105]
  [110 111 112 113 114 115]
  [120 121 122 123 124 125]
  [130 131 132 133 134 135]
  [140 141 142 143 144 145]]

 [[200 201 202 203 204 205]
  [210 211 212 213 214 215]
  [220 221 222 223 224 225]
  [230 231 232 233 234 235]
  [240 241 242 243 244 245]]

 [[300 301 302 303 304 305]
  [310 311 312 313 314 315]
  [320 321 322 323 324 325]
  [330 331 332 333 334 335]
  [340 341 342 343 344 345]]]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8],[9,10],[11,12]])
if arr1.shape[1]!=arr2.shape[0]:
  print('Not possible')
else:
  m=arr1.shape[0]
  n=arr1.shape[1]
  p=arr2.shape[1]
  result=np.zeros((m,p))
  for i in range (m):
    for j in range (p):
      s=0
      for k in range (n):
        s+=arr1[i][k]*arr2[k][j]
      result[i][j]=s
  print(result)


[[ 58.  64.]
 [139. 154.]]
